### ISSUE TITLE
ارور  وصل نشدن

### ISSUE THREAD

**Issue by Armingbz** [AC-Lover/backup#13]
zip warning: name not matched: /usr/local/x-ui/config.json
  adding: etc/x-ui/x-ui.db (deflated 89%)
enter new zip file comment (end with .):
curl: (7) Failed to connect to api.telegram.org port 443 after 23 ms: Connection refused

اين ارورو ميده مشكل چيه

**Comment by AC-Lover** [comment]
درود
یک هشدار داده واسه اینکه فایل config.json توی مسیر /usr/local/x-ui وجود نداره

دوم اینکه نتونسته به تلگرام وصل بشه و این مشکل معمولا بخاطر سرور شماست ، لوکیشن سرورتون ایران هست احیانا؟
