### ISSUE TITLE
ارسال در تایم اشتباه 

### ISSUE THREAD

**Issue by Hsngh01** [AC-Lover/backup#16]
سلام من کرون جاب را 0 1 تنظیم کردم که در هر یک ساعت بکاپ بگیره ولی بحای هر یک ساعت هر دقیقه داره بکاپ میگیره مشکل چیه

**Comment by AC-Lover** [comment]
درود
عدد اول دقیقه ست عدد دوم ساعت

**Comment by Hsngh01** [comment]
> سلام من کرون جاب را 0 1 تنظیم کردم که در هر یک ساعت بکاپ بگیره ولی بحای هر یک ساعت هر دقیقه داره بکاپ میگیره مشکل چیه
