### ISSUE TITLE
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}

### ISSUE THREAD

**Issue by qirmizialma** [AC-Lover/backup#21]
من دو بار انجام دادم و این کد رو میده

**Comment by AC-Lover** [comment]
سلام
ربات رو استارت کنید اگه چت آیدی خودتون رو دادین
اگه هم چت آیدی گروه یا چنل دادین ربات رو ادمین کنید.

**Comment by gapochat** [comment]
> سلام ربات رو استارت کنید اگه چت آیدی خودتون رو دادین اگه هم چت آیدی گروه یا چنل دادین ربات رو ادمین کنید.

مهندس منم دقیقا همین مشکلو دارم. احساس کردم از آی دی عددیه با چند تا آی دی هم تست کردم. چند تا سرورم تست کردم. نشد بازم. همین ارور دوستمونو میده...

**Comment by gapochat** [comment]
> سلام ربات رو استارت کنید اگه چت آیدی خودتون رو دادین اگه هم چت آیدی گروه یا چنل دادین ربات رو ادمین کنید.

میشه یه کمکی بکنین؟

**Comment by gapochat** [comment]
> سلام ربات رو استارت کنید اگه چت آیدی خودتون رو دادین اگه هم چت آیدی گروه یا چنل دادین ربات رو ادمین کنید.

خوب قسمت ایشو ها رو جمعش کنین شما که قرار نیست پاسخگو باشین...
