### ISSUE TITLE
کرون جاب

### ISSUE THREAD

**Issue by Hoseinsjrad** [AC-Lover/backup#4]
سلام به اشتباه کرونجاب رو روی 6 دقیقه ست کردم که قصد من 6 ساعت بود
حالا چطور میتونم تغییرش بدم؟

**Comment by AC-Lover** [comment]
> سلام به اشتباه کرونجاب رو روی 6 دقیقه ست کردم که قصد من 6 ساعت بود
> حالا چطور میتونم تغییرش بدم؟

سلام دوباره اسکریپت رو اجرا کنید و سوال آخر رو y جواب بدین

**Comment by Hoseinsjrad** [comment]
تشکر بابت پاسخ سریع
یه راه دیگ پیدا کردم و اجرا کردم با دستور 
crontab -e 
تونستم کرونجاب رو ادیت کنم 3>
