### ISSUE TITLE
لوکیشن های کاستوم شده 

### ISSUE THREAD

**Issue by pr381s** [AC-Lover/backup#6]
سلام وقت بخیر 
ببخشید ما لوکیشن فایل x-ui.db مون در اون لوکیشن پیشفرض نیست و در پوشه دیگه‌ایی هست
باید چیکار کنیم که بکاپ برای ما دریافت و ارسال بشه ؟ در حال حاضر با این خطا روبرو می‌شیم.
[https://ibb.co/TwK0tBM](url)

**Comment by AC-Lover** [comment]
درود
لینکتون باز نمیشه
ولی خب مسیر دیتابیس کجاست مگه؟

**Comment by pr381s** [comment]
مسر دیتابیس ما به این صورت هست. 
opt/freedom/x-ui/db/x-ui.db

**Comment by AC-Lover** [comment]
> مسر دیتابیس ما به این صورت هست. 
> opt/freedom/x-ui/db/x-ui.db

آپدیت بعدی اینو اضافه میکنم
ولی خب شما میتونید فایل `ac-backup-x.sh` رو ادیت کنید و این مسیر رو اضافه کنید

**Comment by pr381s** [comment]
اعمال کردم و درست شد خیلی ممننونم بابت این اسکریپت کاربردی

**Comment by AC-Lover** [comment]
اسکریپت آپدیت شد و مسیری که گفتین اضافه شد.
