### ISSUE TITLE
کار نمیکنه

### ISSUE THREAD

**Issue by totem2** [AC-Lover/backup#7]
سلام وقت بخیر بعد از اینکه کرونجاب مشخص کردم این پیغام ها ظاهر میشه ولی بکاپ ارسال نمیشه
Cronjob (minutes and hours) (e.g : 30 6 or 0 12) :
24 0
x-ui or marzban or hiddify? [x/m/h] :
m
Would you like the previous crontabs to be cleared? [y/n] :
y
The folder exists at /opt/marzban
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
zip is already the newest version (3.0-12build2).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
  adding: opt/marzban/docker-compose.yml (deflated 35%)
  adding: var/lib/marzban/certs/ (stored 0%)
  adding: var/lib/marzban/certs/.cer (deflated 37%)
  adding: var/lib/marzban/certs/.cer.key (deflated 15%)
  adding: var/lib/marzban/db.sqlite3 (deflated 78%)
  adding: var/lib/marzban/xray_config.json (deflated 84%)
  adding: opt/marzban/.env (deflated 47%)
enter new zip file comment (end with .):
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
Done

**Comment by AC-Lover** [comment]
سلام
ریا ربات رو استارت نکردید یا چت آیدی اشتباهه
لطفا بررسی کنید
