### ISSUE TITLE
سرور ایران

### ISSUE THREAD

**Issue by Hoseinsjrad** [AC-Lover/backup#8]
سلام
در صورتی که روی سرور ایران پنل داشته باشیم 
و تلگرام قیلتره
راهی هست که از کدتون استفاده کنم؟

**Comment by AC-Lover** [comment]
درود
بله
از یک اند پوینتی که فیلتر نیست باید استفاده کنید.

**Comment by Hoseinsjrad** [comment]
چطور؟

**Comment by AC-Lover** [comment]
https://github.com/tdlib/telegram-bot-api

باید اینو روی سرور خارج بیلد کنید بعدش از طرق آی پی میتونید بدون فیلترشکن با بات ارتباط بر قرار کنید
اگر هم نمیتونید و بلد نیستین تلگرام پیام بدین

**Comment by amirnabinejad** [comment]
ای دی تلگرامتون چیه
